name = "KAM"
prefix = "kat"
author = "Katalam, Tomcat, Kygan, YetheSamartaka, Battlekeeper, MJSTIC, Digii / Julian and MiszczuZPolski"
files = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "KAMLogoLowRes.paa",
    "KAMLogoHighRes.paa",
    "AUTHORS.txt"
]


key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip @kat_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[header_exts]
version = "{{git \"id 8\"}}"