name: Documentation

on:
  push:
    branches:
    - wikiUpdate
    
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v3
    - name: Install Python packages
      run: |
        pip3 install wheel
        pip3 install setuptools
        pip3 install pygithub
        pip3 install pygithub3
    - name: Update Translation issue
      if: github.repository == 'KAT-Advanced-Medical/KAM' && ! contains(github.event.head_commit.message, '[ci skip]')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 tools/deploy.py

  draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        if: github.repository == 'KAT-Advanced-Medical/KAM'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Scan for Class Occurrences
        run: |
          python tools/search_classes.py

      - name: Update Wiki
        run: |
          python tools/update_wiki.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
