name: pboProject

on:
  push:
    branches:
    - master
  pull_request_target:

jobs:
  pboproject:
    runs-on: windows-2019
    steps:
    - name: Install Arma 3 Tools
      uses: arma-actions/arma3-tools@master
      with:
        toolsUrl: ${{ secrets.ARMA3_TOOLS_URL }}
    - name: Install Mikero Tools
      uses: arma-actions/mikero-tools@2021-11-06
    - name: Download game data
      run: |
        Invoke-WebRequest "$env:ARMA3_DATA_URL" -OutFile arma3.zip
        $files = @("arma3.zip")
        ForEach ($file in $files) {
          Extract-7Zip -Path $file -DestinationPath .
          Remove-Item $file
        }
      env:
        ARMA3_DATA_URL: ${{ secrets.ARMA3_DATA_URL }}
    - name: Checkout CBA A3
      uses: actions/checkout@v2
      with:
        path: x\cba
        ref: master
        repository: CBATeam/CBA_A3.git
    - name: Checkout ACE3
      uses: actions/checkout@v2
      with:
        path: z\ace
        persist-credentials: false
    - name: Checkout pull request
      uses: actions/checkout@v2
      if: ${{ github.event_name == 'pull_request_target' }}
      with:
        path: pullrequest
        ref: 'refs/pull/${{ github.event.number }}/merge'
    - name: Replace addons with pull request addons
      if: ${{ github.event_name == 'pull_request_target' }}
      run: |
        rm -r x\kat\addons\
        rm -r x\kat\optionals\
        rm -r x\kat\tools\pDummies\
        xcopy /e /h /q pullrequest\addons x\kat\addons\
        xcopy /e /h /q pullrequest\optionals x\kat\optionals\
        xcopy /e /h /q pullrequest\tools\pDummies x\kat\tools\pDummies\
    - name: Setup build environment
      run: |
        subst P: .
        pboproject -P
    - name: Build
      run: py P:\x\kat\tools\make.py ci
      env:
        PYTHONUNBUFFERED: 1
    - name: Archive logs
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: logs
        path: temp/*.log
    - name: Archive @ace
      uses: actions/upload-artifact@v2
      with:
        name: '@kat-${{ github.sha }}'
        path: x\kat\release\@kat
